### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by alim-zanibekov** [nemtrif/utfcpp#100]
It seems that there is an error, I didn’t really understand how it should work, so I can’t make a PR
Line 91
https://github.com/nemtrif/utfcpp/blob/2ad995746bf1731d5e21cde47c9c3deff56bdbc2/source/utf8/checked.h#L86-L92

**Comment by nemtrif** [comment]
What is exactly the problem with the code? Are you getting a compiler warning? If so, would you post the compiler options you use?

**Comment by nemtrif** [comment]
Can't reproduce
