### ISSUE TITLE
Bumping CMake required version

### ISSUE THREAD

**Issue by HerrNamenlos123** [nemtrif/utfcpp#103]
Hi there, I really love this library, it works great!
I have one issue however: With the latest CMake version, it prints an ugly warning, that compatibility will be removed:
```
CMake Deprecation Warning at deps/utfcpp/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
  ```
  
At some point I really want to get rid of this warning for developer-friendliness, but it should be resolved anyways from the point of this library to stay up-to-date.

I see two solutions: Either increase the minimum required CMake version to something reasonable nowadays (like 3.12, 3.16 or similar), or specify a MAX version like the warning suggests. It could be set to 3.16 by writing `cmake_minimum_required (VERSION 3.0.2...3.16)`. This completely removes the warning.

See https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html. If i understand it correctly, this will tell CMake that the library does not need 3.0.2 specifically, but anything in this range. If the version is lower, an error occurs, if the version is between, the policies of the currently installed CMake version will be set, and if the version is even higher than 3.16, the policies for 3.16 will be applied, keeping it compatible for a long time until 3.16 is deprecated as well. If i understand it correctly, it should be set to the highest value that the library is known to work with, so you might just as well set it to 3.27 right away.

Actually, I just saw that many libraries like spdlog and reproc already do this, they have `3.12...3.21`.

Based on that I would suggest changing the version to `cmake_minimum_required (VERSION 3.0.2...3.27)`.

What do you think?

**Comment by nemtrif** [comment]
I can certainly do it.

But why are you even running the utf8 cpp CMake build? Its only purpose is to run the tests. The library itself is header-only - you just include it in your source tree and compile with whatever CMake version you are using.

**Comment by HerrNamenlos123** [comment]
Well, I depend on utfcpp like on dozens of other libraries and all of them are included the same way: `add_subdirectory()` and `target_link_libraries()`. That's it. All I want to say is that my project depends on utfcpp. Everything else is unnecessary implementation details that I do not want to care about. 

I do not want to care about 
 - Where the files are stored
 - Which files to include
 - How they are named
 - And to maintain all of this
 
 I used this library just like this for years and I only realized just recently that it is header-only. I did not even know this fact for a long time, because it is unnecessary to know for me.
 
 Besides that, your CMakeLists.txt is already structured perfectly, so that it can be used for both, why not use CMake if it's already there. Your project itself knows best how to include it. It has all the things: `${IS_ROOT_PROJECT}`, `if (UTF8_TESTS)`, and so on. It certainly looks like it is made for including from a subproject, not just for building unit tests.
 
 As said, it worked perfectly for years for me, it only just recently started spitting out warnings because of the latest CMake version. It would be a significant downgrade to not use it and write my own CMake lines to include the headers instead of using what's already there.

**Comment by nemtrif** [comment]
Alright. I set cmake_minimum_required as you suggested.

Just another question: would implementing https://github.com/nemtrif/utfcpp/issues/54 affect your builds?

**Comment by HerrNamenlos123** [comment]
This PR would indeed affect it because I include the library with #include <utf8.h>. However, I would be happy to change it in the future for the sake of correctness. Currently there is still potential for including the wrong file, which would not be there if it was utfcpp/utf8.h. Same for the CMake name as i mentioned. I am by the way using the library via its tag/release, so it would be great if you could create a new release again when it is finished.

No need to hold back from changes because of me :)

**Comment by HerrNamenlos123** [comment]
Thank you for the change!
