### ISSUE TITLE
cmake dependency totally broken

### ISSUE THREAD

**Issue by neheb** [nemtrif/utfcpp#104]
problem one is that in the generated Targets.cmake file, warnings that should not be exported are:

```
set_target_properties(utf8cpp PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/W4>;\$<\$<NOT:\$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wpedantic;-Wconversion>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/utf8cpp"
)
```

problem two is that on both fedora and debian, the generated ConfigVersion.cmake specifies that it's only for 32-bit, which is nonsense:

```
# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "4")
  math(EXPR installedBits "4 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

this prevents usage with find_package("utf8cpp")

**Comment by neheb** [comment]
Maybe the latter is fixed by https://github.com/nemtrif/utfcpp/pull/101

**Comment by neheb** [comment]
Other fixed by https://github.com/nemtrif/utfcpp/pull/105

**Comment by nemtrif** [comment]
At this point I am seriously considering removing this CMake nonsense, but in the meantime if someone else can confirm there is a problem and #105 fixes it, I'll take the pull request.

**Comment by neheb** [comment]
Which nonsense?

The CMake files should be cleaned up FWIW. tests/CMakeLists.txt should be all using a loop probably.

**Comment by neheb** [comment]
ping
