### ISSUE TITLE
vs2022 C2676 is appearing

### ISSUE THREAD

**Issue by beqabeqa473** [nemtrif/utfcpp#106]
Hello.

Seems i am doing something wrong.
When trying to compile a sample app in vs2022, i get:
utf8\core.h(306,21): error C2676: binary '++': 'octet_iterator' does not define this operator or a conversion to a type acceptable to the predefined operator

What i am doing wrong?

**Comment by nemtrif** [comment]
Would you post the code you are trying to compile?

**Comment by beqabeqa473** [comment]
```
      std::string phonemesStr;
      for (auto phoneme : sentencePhonemes) {
          utf8::append(phoneme, phonemesStr);
      }
```

For some reason i cannot append phoneme to std::string on windows.

**Comment by beqabeqa473** [comment]
Phoneme is of type char32_t

**Comment by synesthesiam** [comment]
Looks like it has to be:

```
utf8::append(phoneme, &phonemesStr);
```

**Comment by synesthesiam** [comment]
I was wrong. It needs to be:

```c++
utf8::append(phoneme, std::back_inserter(phonemesStr));
```
