### ISSUE TITLE
Warnings from -Wsign-conversion on Gcc 11.4.0 with C++ 20

### ISSUE THREAD

**Issue by benblan** [nemtrif/utfcpp#124]
Hello,

when I include the library (v4.0.5) in my code, I get the 2 following warnings. Not sure it comes from my code. Maybe the way I include it?
```
/home/project/extern/utfcpp/utf8/core.h: In instantiation of ‘utf8::internal::utf_error utf8::internal::get_sequence_4(octet_iterator&, octet_iterator, utf8::utfchar32_t&) [with octet_iterator = const char*; utf8::utfchar32_t = char32_t]’:
/home/project/extern/utfcpp/utf8/core.h:277:53:   required from ‘utf8::internal::utf_error utf8::internal::validate_next(octet_iterator&, octet_iterator, utf8::utfchar32_t&) [with octet_iterator = const char*; utf8::utfchar32_t = char32_t]’
/home/project/extern/utfcpp/utf8/core.h:305:45:   required from ‘utf8::internal::utf_error utf8::internal::validate_next(octet_iterator&, octet_iterator) [with octet_iterator = const char*]’
/home/project/extern/utfcpp/utf8/core.h:437:79:   required from ‘octet_iterator utf8::find_invalid(octet_iterator, octet_iterator) [with octet_iterator = const char*]’
/home/project/extern/utfcpp/utf8/core.h:447:28:   required from here
/home/project/extern/utfcpp/utf8/core.h:237:20: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
  237 |         code_point += (utf8::internal::mask8(*it) << 6) & 0xfff;
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/project/extern/utfcpp/utf8/core.h: In instantiation of ‘utf8::internal::utf_error utf8::internal::get_sequence_3(octet_iterator&, octet_iterator, utf8::utfchar32_t&) [with octet_iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; utf8::utfchar32_t = char32_t]’:
/home/project/extern/utfcpp/utf8/core.h:274:53:   required from ‘utf8::internal::utf_error utf8::internal::validate_next(octet_iterator&, octet_iterator, utf8::utfchar32_t&) [with octet_iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; utf8::utfchar32_t = char32_t]’
/home/project/extern/utfcpp/utf8/core.h:305:45:   required from ‘utf8::internal::utf_error utf8::internal::validate_next(octet_iterator&, octet_iterator) [with octet_iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’
/home/project/extern/utfcpp/utf8/core.h:437:79:   required from ‘octet_iterator utf8::find_invalid(octet_iterator, octet_iterator) [with octet_iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’
/home/project/extern/utfcpp/utf8/core.h:452:59:   required from here
/home/project/extern/utfcpp/utf8/core.h:218:20: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
  218 |         code_point += (*it) & 0x3f;
      |         ~~~~~~~~~~~^~~~~~~~~~~~~~~
```

**Comment by nemtrif** [comment]
Would you post a code snippet that causes the warnings?

**Comment by benblan** [comment]
Well, I just have to include the file, I don't have to call some code:
`#include "utf8.h"`

**Comment by benblan** [comment]
Hello,
The second warning:
`/home/project/extern/utfcpp/utf8/core.h: In instantiation of ‘utf8::internal::utf_error utf8::internal::get_sequence_3(octet_iterator&, octet_iterator, utf8::utfchar32_t&) [with octet_iterator = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >; utf8::utfchar32_t = char32_t]’:
/home/project/extern/utfcpp/utf8/core.h:274:53:   required from ‘utf8::internal::utf_error utf8::internal::validate_next(octet_iterator&, octet_iterator, utf8::utfchar32_t&) [with octet_iterator = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >; utf8::utfchar32_t = char32_t]’
/home/project/extern/utfcpp/utf8/checked.h:154:69:   required from ‘utf8::utfchar32_t utf8::next(octet_iterator&, octet_iterator) [with octet_iterator = __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >; utf8::utfchar32_t = char32_t]’
/home/project/engine/src/gfx/font.cpp:158:40:   required from here`

is caused by this code for example:
`void Font::drawText(int x, int y, const std::string& text, bool x2) {
    int sc = x2 ? 2 : 1;
    int ox = x;

    std::string newText(text);
    std::string::iterator b = newText.begin();
    std::string::iterator e = newText.end();
    while ( b != e ) {
        try {
            auto codePoint = utf8::next(b,e);
            //...
        } catch (const utf8::invalid_utf8& exc) {
            continue;
        }
    } //end of while
}
`

**Comment by nemtrif** [comment]
Can't reproduce with GNU 13.1. Can you send me the complete compiler command line?

**Comment by benblan** [comment]
Hi,
is it possible that you build the project ? I'm using Cmake so the real compiler command line is a bit complex to obtain.
My repo is here : https://sourceforge.net/p/freesynd/freesynd/ci/main/tree/
Instruction to build from source code is : https://sourceforge.net/p/freesynd/freesynd/ci/main/tree/INSTALL

**Comment by nemtrif** [comment]
Tried and failed miserably :) Can't find SDL2 even after I installed it. The instructions do mention SDL 1.2, but I don't have it in the apt repository.

**Comment by benblan** [comment]
Sorry about that, it's a mistake in the install file : I have switch to SDL2.
If you want to continue, I have made a lightly more complete installation page : https://sourceforge.net/p/freesynd/wiki/Dev_Env_Install/

**Comment by nemtrif** [comment]
Still no luck. Getting "Unable to locate package libsdl-mixer2-dev" and "Unable to locate package libsdl-image2-dev" on Ubuntu 24.04.1 LTS

**Comment by nemtrif** [comment]
OK. I managed to set -Wsign-conversion on my tests and got a bunch of warnings. Looking into them...

**Comment by nemtrif** [comment]
Alright. 77870cc should fix it.

**Comment by benblan** [comment]
Hi, great! it seems to have fixed the problem. No more warnings.
