### ISSUE TITLE
Homepage at http://utfcpp.sourceforge.net/ points to old repo

### ISSUE THREAD

**Issue by only-a-ptr** [nemtrif/utfcpp#4]
Hello.

I'd like to point out that project's homepage at http://utfcpp.sourceforge.net/ points to outdated sourceforge repo. Further, google search doesn't hit this repository at all (I'm seeing https://github.com/ledger/utfcpp instead).

IMHO the best solution would be to migrate the homepage completely to utfcpp.github.io and delete the SF repository altogether.

**Comment by nemtrif** [comment]
I can't even log on to SF any more. They made some cray requirements for passwords...
