### ISSUE TITLE
Support C++11 features in MSVC

### ISSUE THREAD

**Issue by Flamefire** [nemtrif/utfcpp#42]
Visual studio supports pretty much all C++11 features used here. However up until MSVC 2019(?) it does not correctly define `__cplusplus`.

Could you add an additional check for MSVC so that those features are available there too?

**Comment by nemtrif** [comment]
I don't like the idea of a specific check for MSVC, but can add a define that would enable users to specify the C++ standard they want to use.

**Comment by nemtrif** [comment]
Fixed at: b1002fd198f8251cb1b55ad78bc13fbdd1f9ae84
