### ISSUE TITLE
#include "utf8/cpp11.h" doesn't compile...

### ISSUE THREAD

**Issue by tvanriper** [nemtrif/utfcpp#43]
Steps used to reproduce:

1. Install g++ 8.3.
2. Create a project that conforms to the C++17 standard (makefile, whatever).
3. Create a simple int main(int argc,char** argv){} and #include <utf8.h>

Expected result:

Compiles without issue.

Actual result:

Fails on line 324 of utf8/checked.h because the compiler is told to include utf8/cpp11.h as a path relative to utf8/checked.h.

Expected resolution:

Modify the #include to read: 

`#include "cpp11.h"`

**Comment by nemtrif** [comment]
Did you add the UTF-8 root directory to the list of includes?

**Comment by tvanriper** [comment]
I did.
