### ISSUE TITLE
Warning C4244 when building with MSVC 2019

### ISSUE THREAD

**Issue by Su1c1d0** [nemtrif/utfcpp#45]
**Setup:** 
latest version utfcpp on windows, x86-Debug (or any other) build with latest visual c++ 2019, with /std:c++17 flag
Not sure if problem is in my code or not.

**Problem:**
Project builds fine, however there's a warning in utf8/checked.h (line 151)

> warning C4244: 'argument': conversion from 'const wchar_t' to 'utf8::uint8_t'
---- 
> reference to function template instantiation at checked.h (line 200) 'utf8::uint32_t utf8::next<octet_iterator>(octet_iterator &,octet_iterator)' being compiled
>           with
>           [
>               octet_iterator=const wchar_t *
>           ]
----
> reference to function template instantiation in my own code: 
> 'std::_Iterator_traits_pointer_base<_Ty,true>::difference_type utf8::distance<const wchar_t*>(octet_iterator,octet_iterator)' being compiled
>           with
>           [
>               _Ty=const wchar_t,
>               octet_iterator=const wchar_t *
>           ]

**Proposed solution:**
a simple `static_cast<uint8_t>` at utf8/checked.h (line 151) fixes the problem

**Comment by nemtrif** [comment]
Would you post a code snippet that illustrates the problem? It seems you are using wchar_t for a UTF-8 string, and if that is the case, the problem is in your code.

**Comment by Su1c1d0** [comment]
I have to main use cases - conversion from a char array to a wchar_t array, and vice versa, with side of wchar_t taken as consideration. I anticipate required memory by doing `utf8::distance` in both cases, and I suspect that is the problem.
Convertion for the two cases looks like this:
```
// from char*; to wchar_t*
		try {
			#if WCHAR_MAX > 0xffff
				result = (PC_P2N(utf8::utf8to32(from, from + count, to)) - PC_P2N(to)) / 4;
			#elif WCHAR_MAX > 0xff
				result = (PC_P2N(utf8::utf8to16(from, from + count, to)) - PC_P2N(to)) / 2;
			#else
				pcCopyMemory(from, to, count);
				return result;
			#endif
		}
		catch (utf8::exception& e) {...}
```
---
```
// from wchar_t*; to char*
		try {
			#if WCHAR_MAX > 0xffff
				result = (PC_P2N(utf8::utf32to8(from, from + count, to)) - PC_P2N(to));
			#elif WCHAR_MAX > 0xff
				result = (PC_P2N(utf8::utf16to8(from, from + count, to)) - PC_P2N(to));
			#else
				pcCopyMemory(from, to, count);
				return result;
			#endif
		}
		catch (utf8::exception& e) {...}

```

**Comment by Su1c1d0** [comment]
Yes, you're completely correct. It's my fault - I've misread the manual. :) 
Thank you for the feedback, I'm closing this. :)
