### ISSUE TITLE
Optimization problem with MSVC

### ISSUE THREAD

**Issue by equalent** [nemtrif/utfcpp#46]
Hello!

MSVC:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64
Microsoft (R) Incremental Linker Version 14.21.27702.2
```

The problem happens with this code:
```cpp
FORCEINLINE const char32_t& String::operator[] ( uint32_t Index )
{
  char* first = m_buffer;
  char* last = m_buffer + Size ();
  utf8::advance ( first, Index, last );
  return utf8::peek_next ( first, last );
}
```

`m_buffer` is a `char*` with a UTF8-encoded string and `FORCEINLINE` is simply `inline`. 

Here is my test (I replaced Russian word to "hello!" for convenience but it doesn't change the result):
```cpp
TEST ( RuntimeCore, UTF8Char1 )
{
  const char* str_raw = _T("hello!");
  std::cout << "Raw string: " << str_raw << "\n";
  Wrench::String hello ( str_raw );
  char32_t z = hello[2];
  EXPECT_EQ ( z, U'l' );
}
```
`_T` simply adds `u8` string literal.

And this is the result when the code was compiled with `/O1` (actually, it doesn't really matter because only `/Od` solves the problem):

```
[ RUN      ] RuntimeCore.UTF8Char1
Raw string: hello!
***\Tests\Tests_Core.h(25): error: Expected equality of these values:
  z
    Which is: 3900834211
  U'l'
    Which is: 108
```

As you can see, `z` value is completely different when optimization is enabled (it is the same with `/Od`). It is also different on each execution (without rebuilding) which makes me completely unaware of what's happening in the code :(

**Comment by nemtrif** [comment]
Can you supply a self-contained piece of code that reproduces the problem?

**Comment by equalent** [comment]
Yes, here it is.

```cpp
char* first = u8"hello";
char* last = first + 6;
utf8::advance ( first, 2, last );
char32_t result = utf8::peek_next ( first, last );
```

`result` with `/Od`: 108

`result` with any other optimization mode: different value on each execution

**Comment by equalent** [comment]
I apologize for opening this issue. It was a problem on my side that involved references.

It has nothing to do with utfcpp.
