### ISSUE TITLE
CESU-8 to UTF-8 conversion

### ISSUE THREAD

**Issue by Shebuka** [nemtrif/utfcpp#6]
Hi! I need the possibility to convert from CESU-8 to UTF-8.
CESU-8 is the format we get from MySQL (and Oracle) DBMS and while we were using code point in the range U+0000 to U+FFFF all were OK [(for this range CESU-8 is equal to UTF-8)](https://en.wikipedia.org/wiki/CESU-8), but the things get messed up as one user used a Unicode supplementary character "THINKING FACE" emoji that was returned from DB as [eda0beedb494 (CESU-8) instead of f09fa494(UTF-8)](http://www.fileformat.info/info/unicode/char/1F914/charset_support.htm)...
Can you please provide this functionality?

**Comment by nemtrif** [comment]
Supporting CESU-8 is not in the scope of the library.

**Comment by Shebuka** [comment]
You have in description "In order to easily handle UTF-8 encoded Unicode strings, I came up with a small generic library" and CESU-8 is (wiki) "The Compatibility Encoding Scheme for UTF-16: 8-Bit (CESU-8) is a variant of UTF-8 that is described in Unicode Technical Report".

So if you have a generic library that handles UTF-8 encoded Unicode strings, handling a variant of UTF-8 that is described in Unicode Technical Report can be easily part of the scope of the library...
