### ISSUE TITLE
Current homepage points to sourgeforge project

### ISSUE THREAD

**Issue by adrianbroher** [nemtrif/utfcpp#64]
Hi,

the current [homepage](http://utfcpp.sourceforge.net/) points to the sourceforge project page, which in turn only contains a small link to a blog post, which points to this repository.

When searching, for example, with google, this does not always make clear that this is the official source repository as sometimes [this repository](https://github.com/ledger/utfcpp) is listed as better match.

**Comment by nemtrif** [comment]
The official homepage for the project is https://github.com/nemtrif/utfcpp . That said, you are right - googling sometimes still points to the old SF place. I'll see if I can remove it. Frankly, I can't even log in there any more...

**Comment by nemtrif** [comment]
All my attempts to retrieve SourceForge login credentials failed.
