### ISSUE TITLE
Proper way to make `toupper` and `tolower` for utf8 std::string

### ISSUE THREAD

**Issue by fnc12** [nemtrif/utfcpp#65]
I didn't find it in readme and in issues. Looks like this functionality is not included and I must write it on my own. If so what is the best way to do it? Do I need to iterate every character and call `std::towupper` or there is some other way? Thanks

**Comment by nemtrif** [comment]
Unfortunately, there is no standard way of doing this. You may try setting locale to something like 'en_US.UTF8' and then call toupper on the entire string, but it is most likely not going to work on some systems (Windows in particular). Of course, you can always construct such mapping yourself from the Unicode database (search unicode.org for "case mapping" or "case folding") but it is not trivial.
