### ISSUE TITLE
Can you add a function to calculate the "display width" of UTF8 string?

### ISSUE THREAD

**Issue by p-ranav** [nemtrif/utfcpp#68]
I hope this is in the scope of this project. 

Can you add a function that calculates the "display width" of the UTF string? By display width I mean the "number of columns that the text would take up when displayed in the terminal". This is especially useful when trying to correctly render East-Asian characters in aligned tabular form on the terminal.

This is not the same as the string length (number of multi-byte characters). 

This can be done by using [wcswidth](https://pubs.opengroup.org/onlinepubs/009695399/functions/wcwidth.html) in *nix.

Thanks.

**Comment by nemtrif** [comment]
You mean like https://github.com/p-ranav/unicode_display_width ?

Can that library work directly with utf8 cpp iterators?
