### ISSUE TITLE
utf8::range adapter

### ISSUE THREAD

**Issue by alexeyr** [nemtrif/utfcpp#70]
Just like there is an `utf8::iterator` adapter, I think it would be nice to have an `utf8::range` so as to write

    std::string str = ...;
    utf8::range<std::string> codepoints(str);
    for(char32_t cp : codepoints) { ... }

Or even

    std::string str = ...;
    for(char32_t cp : utf8::make_range(str)) { ... }

**Comment by nemtrif** [comment]
To be honest, I don't know anyone who uses even the iterators. Would it be C++20 only?

**Comment by alexeyr** [comment]
No, C++11 is enough I believe. It just needs to define `begin` and `end` (as free functions or members) returning the iterators, something like (not tested)

    template<typename T>
    struct range {
       T base_range;
    }

    template<typename T>
    begin(range<T> range) -> decltype(begin(range.base_range)) {
        return iterator(begin(range.base_range), begin(range.base_range), end(range.base_range));
    }

    template<typename T>
    end(range<T> range) -> decltype(begin(range.base_range)) {
        return iterator(end(range.base_range), begin(range.base_range), end(range.base_range));
    }

Actually, now I see I could have defined it myself and checked it works, maybe if I need to refine that code...
