### ISSUE TITLE
Macro names should have a prefix

### ISSUE THREAD

**Issue by pitrou** [nemtrif/utfcpp#72]
`utfcpp` defines some macro names such as `NOEXCEPT`. Unfortunately, those can clash with similar macros defined in other projects/libraries. It would be nice if all macros were qualified, e.g. `UTF_CPP_NOEXCEPT`.

**Comment by nemtrif** [comment]
Resolved: https://github.com/nemtrif/utfcpp/commit/3c85cd48f01180656b089369fd2c2cbc4c9e5147

**Comment by pitrou** [comment]
Wow, thank you :-)
