### ISSUE TITLE
add ANSI support

### ISSUE THREAD

**Issue by chipsethan** [nemtrif/utfcpp#81]
// an example of UTF8<-->ANSI

#if defined _WIN32 || defined _WIN64
#include <windows.h>

// utf8 --> Windows-1252
std::string to_ansi(const std::string& utf8)
{
  int wlen = MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, NULL, 0);
  std::wstring wstr(wlen, static_cast<wchar_t>('\0'));
  MultiByteToWideChar(CP_UTF8, 0, utf8.c_str(), -1, &wstr[0], wlen);
  int len = WideCharToMultiByte(CP_ACP, 0, wstr.c_str(), -1, NULL, 0, NULL, NULL);
  std::string ansi(len, '\0');
  WideCharToMultiByte(CP_ACP, 0, wstr.c_str(), -1, &ansi[0], len, NULL, NULL);
  if(!ansi.empty() && static_cast<int>(0 == ansi.back()))
    ansi.pop_back();
  return ansi;
}

// Windows-1252 --> UTF-8
std::string ansi2utf8(const std::string& ansi)
{
  int wlen = MultiByteToWideChar(CP_ACP, 0, ansi.c_str(), -1, NULL, 0);
  std::wstring wstr(wlen, static_cast<wchar_t>('\0'));
  MultiByteToWideChar(CP_ACP, 0, ansi.c_str(), -1, &wstr[0], wlen);
  int len = WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, NULL, 0, NULL, NULL);
  std::string utf8(len, '\0');
  WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, &utf8[0], len, NULL, NULL);
  if(!utf8.empty() && 0 == static_cast<int>(utf8.back()))
    utf8.pop_back();
  return utf8;
}

#endif

**Comment by nemtrif** [comment]
The purpose of this library is only to handle Unicode encodings. Converting from various legacy encodings is simply too much for me to cover.
