### ISSUE TITLE
Consider using _MSVC_LANG to detect cpp version

### ISSUE THREAD

**Issue by depler** [nemtrif/utfcpp#85]
Visual Studio has very conservative approach for macro `__cplusplus`. Even when used with `/std:c++17` switch it still shows this:

![image](https://user-images.githubusercontent.com/13541699/144207011-b13f01e1-7612-40b1-8157-9848f8fc4f04.png)

So by fact Visual Studio will not use `cpp17.h` header without forcing value `UTF_CPP_CPLUSPLUS ` to `201703L`. For windows it is better to use this:

```
#if (defined(_MSVC_LANG) && _MSVC_LANG >= 201703L)
//whatever
#endif
```
Related issue in transmission: https://github.com/transmission/transmission/issues/2256

**Comment by nemtrif** [comment]
I really don't want to chase compiler-specific corner cases.

Setting UTF_CPP_CPLUSPLUS to 201703L is the way to address the issue.

**Comment by Margen67** [comment]
Related: #42
