### ISSUE TITLE
FTBFS due to undocumented external dependency

### ISSUE THREAD

**Issue by LukasSedlak** [nemtrif/utfcpp#88]
The library Fails To Build From Source with following error
```
[ 18%] Building CXX object tests/CMakeFiles/noexceptionstests.dir/test_unchecked_api.cpp.o
/home/lukas/spe5/utfcpp/tests/test_unchecked_api.cpp:1:10: fatal error: ../extern/ftest/ftest.h: No such file or directory
    1 | #include "../extern/ftest/ftest.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Steps to reproduce:
1) Get source code
```
$ git clone https://github.com/nemtrif/utfcpp.git
```
2) Create separate build directory
```
$ cd utfcpp
$ mkdir build
```
3) Configure and build it
```
$ cd build
$ cmake ..
$ make
```

### Environment:
- Ubuntu 20.04 LTS
```$ uname -a
Linux hst02 5.10.0-1051-oem #53-Ubuntu SMP Thu Oct 28 08:11:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Recommendation
The compilation finishes successfully after another repository is checked out with
`utfcpp/extern$ git clone https://github.com/nemtrif/ftest.git`
and re-run the make again.

Still, this is unexpected behaviour. I suggest to add the necessary commands into documentation. Either directly to README or into separate INSTALL file.

**Comment by fu7mu4** [comment]
The utfcpp project uses submodule. I think that you can use `git clone` with `--recursive` option to get dependency that written in .gitmodules on top directory.

```bash
git clone --recursive https://github.com/nemtrif/utfcpp.git
```

Or you can run bellow `git submodule` command after running `git clone`.

```bash
git clone https://github.com/nemtrif/utfcpp.git
cd utfcpp
git submodule update --init --recursive
```

On my environment (macOS), I've done it.

```bash
git clone https://github.com/nemtrif/utfcpp.git
cd utfcpp/
mkdir build
cd build/
cmake ..
make # -> failed
git submodule update --init --recursive
cmake ..
make  # -> success
```

**Comment by nemtrif** [comment]
@fu7mu4 is correct. This is just a common usage of git submodules which is documented here: https://git-scm.com/book/en/v2/Git-Tools-Submodules
