### ISSUE TITLE
Support for u8string?

### ISSUE THREAD

**Issue by XCI9** [nemtrif/utfcpp#89]
In c++20, u8string is added.
Is there any plans to add convertion between std::string and std::u8string,
and also support something like 
std::u8string utf8::utf16to8(std::u16string)?

**Comment by nemtrif** [comment]
Sorry for the late answer.

I am planning to add support for std::u8string in release 4.0. But I am not sure what do you mean by "conversion between std::string and std::u8string". What encoding would you expect the std::string to be?

**Comment by XCI9** [comment]
Encoding of std::string is also utf8, I just mean the type convertion between std::u8string and std::string, i.e. something like 
`std::string utf8::utf8tostr(std::u8string)`
I am currently facing some problems like [this](https://stackoverflow.com/questions/55556200/convert-between-stdu8string-and-stdstring).

Thanks in advance for the update.

**Comment by nemtrif** [comment]
Fixed in release 4.0.0
